stages:
  - build

rust:
  stage: build
  image: rust:slim
  script:
    - apt-get update
    - apt-get install -y pkg-config libssl-dev
    - cargo build --verbose --release
    - cargo test --verbose --release
  artifacts:
    paths:
    - target/release/piproxy
