stages:
  - build

rust:
  stage: build
  image: rust:latest
  rules:
  - when: manual
  script:
    - apt-get update
    - apt-get install -y cmake
    - cargo build --verbose
    - cargo test --verbose
    - cargo build --verbose --release
    - cargo test --verbose --release
    - cargo build --verbose --profile prod
    - cargo test --verbose --profile prod
  artifacts:
    paths:
    - target/debug/piproxy
    - target/release/piproxy
    - target/prod/piproxy
