[package]
name = "load_balancer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait="0.1"
pingora = { version = "0.2", features = [ "proxy", "cache" ] }
bytes = "1.6.0"
once_cell = "1.19.0"
log = "0.4.21"
clap = { version = "4.5.7", features = ["derive"] }
parse-size = "1.0.0"
