name: Rust build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Rust build
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  create_release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-rust]
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: dist/*
        draft: false
        prerelease: false
